#!/bin/bash

DIR=$(dirname $0)

source $DIR/.. 2>/dev/null

core_package() {
    pip3 install --user pywal
    export PATH="${PATH}:${HOME}/.local/bin"
}

core_script(){
    cp -rf $DIR/randwal.py ${HOME}/.local/bin/randwal

    sed -i s/user/$(whoami)/g ${HOME}/.local/bin/randwal
}

persist_on_reboot() {
    cp -rf $DIR/config/randwal.desktop ${HOME}/.config/autostart

    sed -i s/user/$(whoami)/g ${HOME}/.config/autostart/randwal.desktop
}
